### PR TITLE
Portuguese language update

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Unfuzz single string update

### CODE REVIEW

**Comment by johnclause** [comment]
Strange, I did this change manually, so that you would not have to update, and I removed 'fuzzy' manually too. It did not work for some reason, you still had to update ... sorry.

**Comment by pedro-mendonca** [comment]
:+1:

**Comment by johnclause** [comment]
It appeared that I forgot to push my changes of pt_PT and that is why you had to update. Now I got conflict and resolved it in an awkward way (I did not have experience so far in resolving conflicts on github). Hopefully, I did not break your files in the latest update ...

**Comment by pedro-mendonca** [comment]
I'll check it, go check my latest PR, hope you like it :)

**Comment by pedro-mendonca** [comment]
Checked the .po file, it's fine, just updated it!

**Pull request merged**
