### PR TITLE
Allow themes and plugins to add their own custom content hooks

### PR DESCRIPTION
**Pull request by funkjedi**
Trigger a custom event when `addCustomContentHooks` is called to allow themes and plugin developers to add their own custom content hooks.

Usage example:
```js
jQuery(document).on('qTranslateX:addCustomContentHooks', function(event, qtx, form) {

	jQuery('.acf-field-text .acf-input-wrap input').each(function() {
		qtx.addContentHookById(this.id, form);
	});

});
```

### CODE REVIEW

**Comment by johnclause** [comment]
Hi Tim, this is an interesting idea - thank you. I am also trying to implement the best possible way to integrate and that is being developed like every day. Have you seen the code of plugins:

https://github.com/qTranslate-Team/woocommerce-qtranslate-x
https://github.com/qTranslate-Team/wp-seo-qtranslate-x
https://github.com/qTranslate-Team/events-made-easy-qtranslate-x

The last one, events-made-easy, is incomplete, but it has the most of comments and explanations, since I was preparing it for the author of Events Made Easy (https://wordpress.org/plugins/events-made-easy/) to finish the code.

The idea is that, eventually, users and plugin authors will be able to submit a custom configuration as an xml or json text or file, which will describe the fields need to be translatable. For now, we code the array needed and submit it through a hook.

I believe you can achieve what you need with already existent hooks, following the pattern of the plugins mentioned above.

Please, take a look and let me know what you think.

**Comment by funkjedi** [comment]
Brilliant worked like a charm.

**Comment by johnclause** [comment]
Hi Tim, were you able to complete all what you need? Which plugin is that? Should I listed it on the Description page as an example of integration?

**Comment by funkjedi** [comment]
The `qtranslate_load_admin_page_config` filter did the job splendidly. The plugin's called [ACF qTranslate](https://wordpress.org/plugins/acf-qtranslate/) and absolutely feel free to put it as an example.

**Comment by johnclause** [comment]
I listed it on the description page. I believe you have made many people happy with this plugin! Thank you.

**Pull request closed without merging**
