### PR TITLE
Update widget to HTML5 specs

### PR DESCRIPTION
**Pull request by acidicX**
- Inline CSS needed to be scoped
- Flags (images) now have an alt description

Widget now passes validation.

### CODE REVIEW

**Comment by johnclause** [comment]
3.2-b2 now has alts for flags. How important is "scopped"? What does get broken? This page http://www.w3schools.com/tags/att_style_scoped.asp says it is only a feature of firefox, is it? I guess, it does not hurt to set it though.

**Comment by acidicX** [comment]
Nothing is actually broken, but it is required for HTML5 pages, otherwise validation fails. Style tags inside the HTML have to be scoped now, which means that the styles only affect everything inside the parent element of the style tag. Btw, MDN is a much better source for specs and browser support than w3schools: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style
e.g.
```html
<h1>test1</h1>
<div id="parent">
<style scoped>h1 { color: white; }</style>
<h1>test2</h1>
</div>
```
test2 will be white, test1 not.
Scoped styles are supported by Chrome and FF.
@mweimerskirch I does not need to be after $before_widget, as widgets are commonly contained by a parent div so the scope is defined... but you could to it, for sure.

**Comment by johnclause** [comment]
The reason `$before_widget` is after style is that it may have some items affected by style. Enclosing `div` in 'Twenty Fifteen' is the whole widget area, while `$before_widget` defines aside tag. Does scope works inside aside? Anyway, @acidicX, could you figure out `if` statement to put `scope` only if browser is firefox? Chrome seems to have tried putting it in, and then removed it, so it looks like this attribute will die sooner or later. Should be bother ourselves with it at all?

**Comment by johnclause** [comment]
I assume we can close it, if you decide to put it in with an appropriate 'if', please, make a new PR.

**Comment by acidicX** [comment]
there is no need for an if. It's in the specs. Other browsers can ignore it.

**Pull request closed without merging**
