### PR TITLE
Fix import / export settings

### PR DESCRIPTION
**Pull request by xhaleera**

### CODE REVIEW

**Comment by johnclause** [comment]
Thank you, @xhaleera, I probably forgot to adjust this after deeper separating front/back files and actions.

Would not this be even better:
```
function qtranxf_migrate_plugin($plugin){
	$var=$plugin.'-migration';
	if(!isset($_POST[$var])) return;
	if($_POST[$var]=='none') return;
	if($_POST[$var]=='export')
		qtranxf_saveConfig();
	$f='qtranxf_migrate_'.$_POST[$var].'_'.str_replace('-','_',$plugin);
	$f();
	if($_POST[$var]=='import')
		qtranxf_loadConfig();
}

function qtranxf_migrate_plugins()
{
	if(!current_user_can('manage_options')) return;
	qtranxf_migrate_plugin('mqtranslate');
	qtranxf_migrate_plugin('qtranslate-xp');
	//qtranxf_migrate_plugin('ztranslate');//ok same db
}
add_action('qtranslate_init_begin','qtranxf_migrate_plugins',11);
```

I also added `if(!current_user_can('manage_options')) return;`.

**Comment by xhaleera** [comment]
I don't exactly understand why you need the saveConfig() part, but the rest seems ok.

**Comment by johnclause** [comment]
Because potentially some other options could have been set at the same time, which are not stored yet. That was my thinking, but I might be wrong, maybe they are always saved already at this point. It has been a while I was working on this. If you already checked that this is excessive, I will remove it.

**Comment by xhaleera** [comment]
No, I've not checked it. You should keep it.

**Comment by johnclause** [comment]
Ok, then it is done, thank you very much, Christophe!

**Pull request closed without merging**
