### PR TITLE
Added Estonian Language to default language list

### PR DESCRIPTION
**Pull request by ddon**
Since I work here with many Estonian clients and I always install qTranslate-X on their blog, I have to manually add Estonian language every time I install this plugin. I hope we can add this language to default list if nobody minds.

### CODE REVIEW

**Comment by johnclause** [comment]
Could you also find someone to do -et_ET.po?

**Comment by ddon** [comment]
will try... a lot of text there to translate :(

**Comment by johnclause** [comment]
Hi Dmitri, I have just come across of Estonian locale and it seems that the standard is 'et_EE', and not 'et_ET' as you specified. Linux command locale lists et_EE and there is no et_ET. Do you think we should change that or you insist that et_ET is correct?

**Comment by ddon** [comment]
http://lh.2xlibre.net/locale/et_EE/
looks like you are right! let's change it of course!

**Comment by johnclause** [comment]
Will be updated on the next release - thanks!

**Pull request merged**
