### PR TITLE
Translation related issues

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Added textdomain to strings that had their textdomain cutted in some commits
Correction to .pot (should be checked the generatiing process so it don't happen again)
Portuguese language update

### CODE REVIEW

**Comment by johnclause** [comment]
Oops, somehow I lost textdomains in the process of update ... sorry ... I will pay attention now how that happens. About `+msgctxt "browser option"`, I can not figure out a way to make `xgettext` pick that one up automatically. I am running it like this:
>xgettext -f tmpfns.txt \
    --from-code=UTF-8 \
    --sort-by-file \
    --default-domain=default \
    --language=PHP \
    --keyword=__ \
    --keyword=_e \
    --keyword=_x \
    --keyword=esc_attr_e \
    --no-wrap \
    --package-name=qTranslate-X \
    --package-version=$ver \
    --copyright-holder="qTranslate Team" \
    --output lang/qtranslate.pot.raw

I guess, I can add this one, and possibly others in the future, to the script manually, unless you know a better way?

**Comment by pedro-mendonca** [comment]
I only use Poedit, it generates the .pot and captured the context, that's how I found the difference.
If you update the .pot with Poedit it outputs a report of new and deprecated strings.

**Comment by qtranslateteam** [comment]
I am trying to avoid manual step with poedit. I am on linux. I run script
before push and that is all. I updated the script to put this line in with
an additional step. If I get another line like this, the script will need
to be updated, but I guess, it is ok for the moment. I hope you will not
need to regenerate pot file on your own next time. One operation less for
you ;)

**Comment by pedro-mendonca** [comment]
I usually double check source code directly on .po update. I only regenerated the .pot if I find any problem and I did it to alert you that it wasn't grabbing everything needed, and to help you to perfect your automated .pot generating process. Of course I hope in the future it's well synced so we can have less operations, but from my litlle experience, it's always a good idea to double check, it's my contribute on behalf of quality of translations :)

**Comment by qtranslateteam** [comment]
I understand. You are doing absolutely perfect work! Thanks a lot,
Pedro, again and again ;)))

**Pull request merged**
