### PR TITLE
i18n improvements

### PR DESCRIPTION
**Pull request by mweimerskirch**
I fixed a few translatable strings (the translation domain "qtranslate" was missing).
And I added a shell script that makes it much easier to update the language files. It just needs to be run in the "lang" folder. I noticed that the files in the "admin" directory are not included in the current pot/po files.

### CODE REVIEW

**Comment by johnclause** [comment]
Actually, Michel, I purposely left 'Error' and 'Deactivate' to go by WP default translation, since they must have those words already translated. I little less work for our translators, and at least those will be translated for the languages which we do not have translators yet. Do you think it is ok?

**Comment by johnclause** [comment]
As to shell script, I saw that long time ago, and I used it as a starting point for the one I am currently using, which is stored on SVN repository: http://plugins.svn.wordpress.org/qtranslate-x/assets/dev/updateTranslations.sh Thank you very much for the initial script, it was very helpful for me.

We probably should not have it on GitHub though, or we have to design a different place to keep it, since it does not need to be a part of standard distribution, don't you think so? What is a common approach to where to keep auxiliary files on GitHub, which should not go to the main distribution?

**Comment by mweimerskirch** [comment]
> Actually, Michel, I purposely left 'Error' and 'Deactivate' to go by WP default translation, since they must have those words already translated. I little less work for our translators, and at least those will be translated for the languages which we do not have translators yet. Do you think it is ok?

There might be languages where the word order is inverted, so the "%s" has to be inside the string. e.g. "Deactivate %s" would be "%s deaktivieren" in German (although there is also "Deaktiviere %s", but this way the translator can choose).

> As to shell script, I saw that long time ago, and I used it as a starting point for the one I am currently using, which is stored on SVN repository: http://plugins.svn.wordpress.org/qtranslate-x/assets/dev/updateTranslations.sh Thank you very much for the initial script, it was very helpful for me.

I didn't see you version. It is much more extensive than mine, and the sorting options look really useful. "no-wrap" as well. I like it much better like this. You should definitely include those switches in whatever version you end up keeping.

> We probably should not have it on GitHub though, or we have to design a different place to keep it, since it does not need to be a part of standard distribution, don't you think so? What is a common approach to where to keep auxiliary files on GitHub, which should not go to the main distribution?

I think the script should be in the repo. It's just a small text file after all, so it doesn't really use up space, so that's no counter-argument. Having the file there makes it easier for translators to test their translations or for developers to test changes that they work on. As for the location, I'm happy with the "lang" folder, but I could also imagine a "utils", "build" or "scripts" folder along with the other dev scripts.

**Comment by johnclause** [comment]
Ok, I will keep your version of 'Deactivate %s'. What about 'Error', is that one safe? Do you think it is good idea or better to move to 'qtranslate' domain too?

On script location. It is on repo (SVN). Most translators I was in touch with are not developers, some have trouble to use GitHub, most do not use unix, their realm is poedit. I am looking at other plugins, and I do not see any other examples who include maintenance script in the main distribution. Neither they include .po files. WP designed this area 'assets' for the sake of exactly things like this, so experienced users will find it there and we also can have some 'HowTo' published some place for those who would need it. I do not see a similar location, like 'assets' on WP, designed on GitHub. Their realm is different. I was thinking about a separate repository with name like 'qtranslate-x-dev', but I do not feel comfortable about it either. Maybe 'assets' on svn plus a 'HowTo' is the best solution for now? Even for po files too?

Actually, WP must have some rules already designed on the best way to distribute .po files. I have not learned those yet.

Thanks again for all your help, Michel.

**Comment by pedro-mendonca** [comment]
From translator point of view, a string listed should be translated, the goal is always have 100% of strings translated.
Poedit sweeps all the code to include strings, and it does not filter by textdomain neither the ones without textdomain. I think the most usual is to translate it all, even those redundant that are already translated in Wordpress core.
If you want to exclude it, I think you must exclude it manually from .pot file, and this don't make sense.



No dia 21/02/2015, às 15:19, johnclause <notifications@github.com> escreveu:

**Comment by mweimerskirch** [comment]
> Ok, I will keep your version of 'Deactivate %s'. What about 'Error', is that one safe? Do you think it is good idea or better to move to 'qtranslate' domain too?

As @pedro-mendonca says, the extraction tools always include all the strings, even without domain, so you might as well add it. At the same time, it might be good to include the entire sentence (I overlooked that yesterday):

<pre>
__('<strong>Error:</strong></span> plugin %s cannot run concurrently with plugin %s. You may import and export compatible settings between %s and %s on Settings/<a href="%s">Languages</a> configuration page. Then you have to deactivate one of the plugins to continue.',  'qtranslate')
</pre>

French for example uses a not-breaking space before the colon: "Erreur : xxxxxxx"

> On script location. It is on repo (SVN).

What if somebody wants to modify/fix one of the scripts? IMHO, they should also be possible on GitHub.

**Comment by johnclause** [comment]
Ok, this comment closes the discussion. I'll keep it in 'qtranslate' domain. Thanks, Pedro.

**Comment by johnclause** [comment]
@mweimerskirch: Exactly, I was looking at that line just now and thought the same. I will move it. :+1:

**Comment by pedro-mendonca** [comment]
One more thing, I think keeping those html tags and code editable in translation is dangerous, might be better to put it all in several %s.

**Comment by qtranslateteam** [comment]
Same thought here just now too. Your comment ensures me. Thank you, Pedro,
again.

**Comment by mweimerskirch** [comment]
Indeed. Good point.

**Pull request merged**
