### PR TITLE
New readme.md with GitHub markdown for better reading in front qtranslate page.

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Copied readme.txt to readme.md with github markdown

Changed markdown codes to comply to github:
https://help.github.com/articles/markdown-basics/

Changes:
=== TEXT === > # TEXT # (H1)
== TEXT == > ## TEXT ## (H2)
= TEXT = > ### TEXT ### (H3)

PS: Sorry about so many commits, I've made a lot of edits and pushed to my fork to see it rendered in GitHub.
In the end I've deleted and readded the final file, but github sends all these commits.

### CODE REVIEW

**Comment by johnclause** [comment]
>in front qtranslate page

Wordpress or GitHub?

How does that work with Wordpress? Do they allow readme.md instead of readme.txt? Can I now remove readme.txt on next update?

**Comment by pedro-mendonca** [comment]
I think I've seen a lot of .md on wordpress plugins.

Keeping both .txt and .md is redundant but might might be helpfull for different contexts as .md is very helpfull for GitHub render readme a lot better, .txt is the probably the best for one who reads it locally after plugin download.

**Comment by pedro-mendonca** [comment]
I don't know how this works, but I think you might know what to do with this :)
Check out these options from qTranslate-slug:
https://plugins.trac.wordpress.org/browser/qtranslate-slug/trunk

**Comment by pedro-mendonca** [comment]
"Wordpress or GitHub?"
GitHub, check my fork to see it working:
https://github.com/pedro-mendonca/qtranslate-x
It gets a lot more fancy :)

**Comment by johnclause** [comment]
readme.txt is a controlling file for Wordpress. I tried to validate https://raw.githubusercontent.com/pedro-mendonca/qtranslate-x/master/readme.md
with https://wordpress.org/plugins/about/validator/ and I got "URL must end in readme.txt!". However, when I pasted the content of .md into their validator, it appeared to be ok. So, we need to find a way to use the same file for both .txt and .md. Maybe readme.txt would be a link?

**Comment by pedro-mendonca** [comment]
As I saw on qtranslate-slug, both files exist in github, and only .txt is synced to wordpress repo. I don't know this process to help you out, but I found a clue on https://plugins.trac.wordpress.org/browser/qtranslate-slug/trunk, as you can see below:
"Property svn:ignore set to
README.md
Thumbs.db
.git
bin
tests
.gitignore"
The author also keeps markdown different, probably because #, ##, ### it's github style and ===, ==, = have a different impact in .txt visuals.

**Comment by johnclause** [comment]
I made .md to be a link to .txt and will ignore .md on svn check-in. GitHub seems to handle link just fine.

**Comment by pedro-mendonca** [comment]
Great idea!
:+1:

**Pull request merged**
