### PR TITLE
Improved visual integration of language switch

### PR DESCRIPTION
**Pull request by xhaleera**
**WARNING: common.min.js has not been regenerated.**

### CODE REVIEW

**Comment by xhaleera** [comment]
Preview of the proposed rendering (supports WordPress admin customizable color schemes)

capture d ecran 2015-03-01 a 19 22 42

**Comment by johnclause** [comment]
This looks nice, however, knowing how different people are, I will pull this in later as an option of a few choices. Somebody also sent me another CSS to make it look like tabs. So, it will be an option with three choices already, and may be more will come in time. Thanks a lot for this code, it definitely has a good value.

**Comment by mweimerskirch** [comment]
@xhaleera you could make it configurable in a similar way to #90
@johnclause, would you accept it if it's configurable? I'd really like to be able to use the improved layout.

**Comment by johnclause** [comment]
Yes, as I mentioned to you before, I thought that this option would go together with highlighting and "Editor Mode" option on user profile. There is one more CSS preset commented in _configuration.css, so altogether, there are 3 presets for "Language Switching Buttons Style" option, and I would also like to provide opportunity for user to enter their own admin CSS. I was thinking about one only filed for combined CSS, which will be populated with presets chosen from two options, and then user can do further customization on combined admin CSS if desired.

I am still dealing with bugs, more and more rare and more and more particular, but still coming in reports. As soon as I am done I will do those options, and, of course, if somebody decides to help, I will appreciate very much.

**Comment by johnclause** [comment]
Option "LSB Style" is now implemented.

**Pull request closed without merging**
