### PR TITLE
Portuguese update (pt_PT)

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by johnclause** [comment]
Thanks!

**Comment by pedro-mendonca** [comment]
:+1:

**Comment by pedro-mendonca** [comment]
This was just an update to comply with pt_PT translation team syntax. This didn't include the last slugs related strings, because if I sweep the code I'll break the way the .po is structured and explode the ammount of commitdiffs.
I'l wait for .pot update.

**Comment by johnclause** [comment]
Yes, sure, slug part is not ready yet to be translated. There is still a lot to do before it is released.

**Pull request merged**
