### PR TITLE
Modification of qtrans_parseURL and qtrans_use written by normadize to i...

### PR DESCRIPTION
**Pull request by janmolnar**
...mprove performance -- see https://wordpress.org/support/topic/evidence-on-how-slow-and-inefficient-qtranslate-is-please-do-something.

### CODE REVIEW

**Comment by LC43** [comment]
we used much of those modifications on our own qts_use and use parse_url for our parser too. can't say much for performance gain, but using a native function is always a good choice.

**Comment by johnclause** [comment]
Thank you, Jan and Pedro, this is very useful information. I keep finding more and more imperfections too. I will research it all together when I am ready to work on performance issues, after I am done with other recent "fires", reported by users.

**Comment by johnclause** [comment]
BTW, if you got some spare time, you might be curious to solve https://github.com/qTranslate-Team/qtranslate-x/issues/5 . It was always there since original qTranslate and including mqTranslate, and, I would assume, all other forks too.

**Comment by xhaleera** [comment]
I've tried parse_url on mqTranslate a few months ago, but some users get altered behavior and errors, so I reverted to the "original" qtrans_parseURL

**Comment by johnclause** [comment]
Yes, I also figured out that it is not exactly the same, and cannot replace the current implementation without further changes. Besides, this part of code in -x has already been modified a lot, and this PR is no longer applicable. I am closing it now. Thank you, @janmolnar, for submitting it though it was very useful to inspire some ideas.

**Pull request closed without merging**
