### PR TITLE
Translations uptaded

### PR DESCRIPTION
**Pull request by pedro-mendonca**
.pot catalog updated with new strings found.
Portuguese files updated also.

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
I've added this commit https://github.com/pedro-mendonca/qtranslate-x/commit/33e97c1f24971681f5464db810cfcd7bf5195eac to optimize a string I've corrected before, where I've isolated the 'and' for translation. I think it looks and works better like this, cleaner code.

**Comment by johnclause** [comment]
Pedro, do you think comma is an international mark the same for all languages? If so, I would then suggest  "%s and %s" instead of "%s, %s, %s, %s, %s and %s", just to be flexible on the number of functions listed, which may change later. It is not important, but would probably be even more clean?

**Comment by pedro-mendonca** [comment]
I really don't know. Thats why I thought it would be more clear and flexible for each translator to choose the best way to translate it in their language, in portuguese it more or less like english in this case, %s, %, and %s, but there can be some cases that it fits better only with comas or something else. Of course the translator must understand clearly the statement in english to adapt it as he wish.
From the translator point of view, I can say that a complete sentence with variables (%s) is way more clear to understand te context and the meaning.
Of course the translator MUST respect the number of strings, but I think that is verified in Poedit parsing.

**Comment by johnclause** [comment]
Ok, I realised that if we ever need to change number of %s, we can adjust each po file as well without asking somebody to make a new translation, following whatever pattern will will see, so it is not a big deal.  This way is definitely good for any language, while one %s might be indeed a problem for some - you are right.

**Comment by pedro-mendonca** [comment]
If the number of %s will probably change, of course you will need to update the language files, but that is a lot of unnecessary work.
In that case I definitly go for the whole list in one simple %s, with no descriptive text needed to translate, making it a more technical list.

Instead of **"Enable function names compatibility for %s, %s, %s, %s, %s and %s."**
Go for  **"Enable function names compatibility for listed funcions (%s)."** where %s is coded without any text like "func_a; func_b; func_c; func_d**(; func_n)"**.

**Comment by johnclause** [comment]
May be just simply "Enable function name compatibility (%s)."?

**Comment by pedro-mendonca** [comment]
Yep, thats it. The list in %s of course must only use **;** elements, no english, no text to translate.

**Comment by johnclause** [comment]
Hi Pedro, yes the number of functions already changed, I added qtrans_generateLanguageSelectCode, so our discussion here was not completely useless :+1:

**Comment by pedro-mendonca** [comment]
+1
Closing this tread.

**Pull request merged**
