### PR TITLE
Load translations manually in the widget constructor

### LINKED ISSUE #43: Widget 'qTranslate Language Chooser' not translated
The widget is not getting language files, shows english text.

### PR DESCRIPTION
**Pull request by mweimerskirch**
otherwise the translations are not available inside the constructor.

Fixes #43

### CODE REVIEW

**Comment by johnclause** [comment]
Why it is not available? Is constructed called too early, of textdomain is set too late? Should not we reconcile their sequence? Otherwise, what if we add another widget, we will have to set text domain in each of them? This does not seem to be quite right, does it?

**Comment by pedro-mendonca** [comment]
Correct.
I've already tried this solution. Of course it works but I cannot consider it the best way, precisely because it's not identified the cause and it can happen again in some other file.
I'm sure you'll find it's origin now :)

**Comment by mweimerskirch** [comment]
I tried changing the priorities, but this is the only way it works. I had a look at a few other plugins (Akismet, GravityForms, ...). They do it the same way. No idea why though :-(

**Comment by pedro-mendonca** [comment]
Same here, changed order of php files loading and in the end tried that doble textdomain call in widget.

**Comment by johnclause** [comment]
It is strange indeed, but no there is no time to figure it out, so let it be in for now.

**Comment by johnclause** [comment]
Actually, https://codex.wordpress.org/Function_Reference/load_plugin_textdomain seem to recommend to run `load_plugin_textdomain` in 'plugins_loaded' action, so I moved it and it seems to have helped. Let see what else gets broken :) It will be uploaded in 3.2-b3, not yet there.

**Comment by pedro-mendonca** [comment]
It's ok now, everything translated, core, menu and widget.

**Pull request merged**
