### PR TITLE
Propose a new fresh UI - Tabs!

### PR DESCRIPTION
**Pull request by pedro-mendonca**
The Show/Hide sections isn't very funcional.
It needs a lot of scrolling and a litte ugly.

I've maintained the whoole code, except section navigation.
It uses WordPress native css for Tabs.

Some old organization might need a cleanup, but for now I've maintained everything as is to minimize commit diffs.
I've pushed partial commits to make your work easyer to understand what changed, as the whole diff is too long to understand.

The code was adapted from a living example: WP-Maintenance-Mode tabbed admin settings

There are some issues not solved yet, but I believe you @johnclause are the one who can solve it:
> After saving changes it goes back to first tab.
The original code keeps in same tab after saving, but in this case `<form action="<?php echo $clean_uri;?>" method="post">` is the problem. If `<form>` have `action=""` it works like a charm.
I didn't touch this because I think it's better in your hands from this point beyond.

Please check this out, it really looks way better and works great!
:)

### CODE REVIEW

**Comment by johnclause** [comment]
Hi Pedro, I will play with this after 3.3 release. This seems to be a pretty big change, which I also planned to do one day, I really appreciate that you took the initiative. I thought I would have to change functions qtranxf_admin_section_start/end only for that, but it seems to have taken many more changes. I will review it in a few days. Thanks!

**Comment by pedro-mendonca** [comment]
Yes, of course.
There are two options, the tabs reloading the page and the 5 forms are different, or the tabs are just hidden and shown without reloading.
I don't really know what will you prefer, I just did a change in the shown/hidden sections using the tabs, I did no change at all in the overall structure.
To make it easier, I've made the partial commits with less changes each one.
I took out the qtransf_admin_section_start/end the show/hide beaviour and used basic jquery for the nav tabs. Then I've added the necessary divs wrapping those admin_sections. i did it INSIDE the `<form>` because it's just one for sections1, 2 and 3.
If you want I can try to improve it by puting inside those ..._start/end functions the most part of the wrapping code.

**Comment by qtranslateteam** [comment]
I did not follow through your code yet, and I am still not sure why changes
other than inside _start/end functions (including their arguments) are
needed. I thought I would keep it encapsulated by sections as it is now,
and only re-implement _start/end to show tabs. Is that possible? And I also
thought that I will not ask people to reload page to change a tab, your
second option, I guess, this is how you did it too?

**Comment by pedro-mendonca** [comment]
Yes, as I said, the basic structure is the same, so, no reloading.
Looking at it again after the work is done, I think I can move a lot of the section wrapping to _start/end functions. I'll do this and remove the indenting for now, it was necessary for me to understand the code but now I can revert it.

I'll do some changes and add to the current commits, ok?
Meanwhile, I'll keep pushing `master` commits to this branch so that it won't get to far behind and at any moment it can be included in `master`. Because of this some more merging commits will keep apearing and the list will increase, but in the end, the commits diffs will reduce.

**Comment by qtranslateteam** [comment]
>indenting

I use tab size equal to 2. Most editors have an option for tab size, which
helps a lot. Is that what you mean?

**Comment by johnclause** [comment]
It could be easier for you to make a new fork and then to copy relevant pieces from your local copy into   the new fork?

**Comment by pedro-mendonca** [comment]
@johnclause
I just pulled some more commits to this.
I've kept myself within the same branch, locally I've started all over with the current `master` files, changed only the necessary code to switch from Hide/Show to Tabs and commited the file to ui-tabs branch.
This shows a lot of reversing changes in the particular commit because it's on top of previous changes, but as I did it from scratch without the overall code cleaning, the global commit diffs that appear here are the ones I've really made, and are just the simple changes needed to switch GUI to tabs.

Summary:
Included admin container classes in _start/end
included global  that contains the admin sections. There are two of them because you have also two wraps.
Included navigation tabs and necessary jquery script

Please check if it's simpler now.

**Comment by pedro-mendonca** [comment]
After this, I think some stuff can be deleted:
* The function that used to Show/Hide
* The var $section from the function _start is no longer needed as the Section Title is defined in the Navigation Tabs
* The cookie request and function to remember which sections where shown/hidden

**Comment by johnclause** [comment]
Pedro, I am sorry for the delay, I will play with this after 3.3 is out. Otherwise there will be not much new in 3.4 ;)

**Comment by pedro-mendonca** [comment]
That's ok :)
Do you want me to merge the full recent stuff from master in ui-tabs branch to keep it up to date?

**Comment by johnclause** [comment]
I do not know, it still says that it can be merged automatically. I did not change the file affected much and will probably not change before merging this PR.

**Comment by pedro-mendonca** [comment]
Maybe it's because `ui-tabs` branch isn't on top of latest commit on your `master`.
I'm doing an update, it will increase the list of commits above but will be updated on top of current `master`.

**Comment by johnclause** [comment]
oops ... Now it says it cannot merge? What happened?

**Comment by pedro-mendonca** [comment]
It got out of sync because of last updates, give-me a minute to sync it.

**Comment by pedro-mendonca** [comment]
Ok, I see that there are recent changes in the same files, let me rearrange that and I'll notice you.

**Comment by pedro-mendonca** [comment]
This PR is getting very confuse with syncing between 3 branches.
I'm closing this and making a brand new clean PR.

**Comment by pedro-mendonca** [comment]
I've rewritten the code from scratch in a brand new branch and pulled it again in https://github.com/qTranslate-Team/qtranslate-x/pull/153

**Pull request closed without merging**
